- badge_server/badge_server.py
- badge_server/deployment/app-with-secret.yaml
- badge_server/requirements.txt
- compatibility_lib/setup.py
> Change to use Memorystore for caching

- nox.py
- system_test/test_compatibility_checker_server.py
> Add system test for compatibility checker server

- grid-template.html
> Display compatibility checker result in a dialog

- compatibility_lib/setup.py
Bump the version number to 0.0.5.
> Prepare for compatibility_lib 0.0.5 release

- badge_server/badge_server.py
- compatibility_lib/compatibility_lib/dependency_highlighter.py
- compatibility_lib/compatibility_lib/test_dependency_highlighter.py
- nox.py
- requirements-test.txt
also refactored dependency highlighter for usage in badge server
> Adding dependency badging

- dashboard/grid-template.html
> Make the dialog display the details better

- dashboard/dashboard_builder.py
- dashboard/grid-template.html
- dashboard/main-template.html
> Backend for getting dependencies need to update

- badge_server/badge_server.py
- badge_server/static/css/theme.css
- badge_server/templates/google-compatibility.html
- badge_server/templates/self-compatibility.html
- Result for Python2:
- Result for Python3:
> Add package page for google compatibility check result

- badge_server/badge_server.py
- badge_server/static/css/theme.css
- badge_server/templates/dependency-result.html
- dashboard/main-template.html
> Add badge page for dependency check

- badge_server/badge_server.py
- badge_server/templates/dependency-result.html
> Add deprecated_dep tab to dependency badge page

- badge_server/badge_server.py
- badge_server/templates/one-badge.html
- system_test/test_badge_server.py
Fixes #126 
This also changes the usage of calling badge server endpoint:
`.../image/...` -> `..._image/...`
> Support one badge usage

- dashboard/main-template.html
> fix copyright

- badge_server/badge_server.py
> Sanitize github head package name

- dashboard/main-template.html
We could do a little more in the code to select different verbs depending on whether there's one (singular) or multiple (plural) changes needed, but for the results we have now this works.
> Mostly subject verb agreement

- dashboard/grid-template.html
> font element not supported in HTML 5

- dashboard/main-template.html
@liyanhui1228 Not sure if anything still pays attention to metadata like this in 2018, but if so it should describe the page, not the template.
> Remove meta elements

- badge_server/main.py
- best_practices/README.rst
- compatibility_lib/compatibility_lib/compatibility_checker.py
- compatibility_lib/compatibility_lib/dependency_highlighter.py
- compatibility_lib/compatibility_lib/test_compatibility_checker.py
- compatibility_lib/compatibility_lib/test_utils.py
- compatibility_lib/compatibility_lib/utils.py
- system_test/test_badge_server.py
And raise PackageNotSupported exception for those packages.
> Set status to UNKNOWN when package is not in whitelist

- README.rst
- compatibility_lib/compatibility_lib/configs.py
- compatibility_server/configs.py
- compatibility_server/test_sanitize_packages.py
- update badge image url to compatibility-lib instead of compatibility_lib
- unquote whitelist urls
> fix badge issues

- badge_server/main.py
- badge_server/templates/one-badge.html
- badge_server/utils.py
- compatibility_lib/compatibility_lib/get_compatibility_data.py
- compatibility_lib/compatibility_lib/test_get_compatibility_data.py
- compatibility_lib/compatibility_lib/utils.py
> Cache the github head version result based on commit number

- compatibility_lib/compatibility_lib/compatibility_checker.py
- compatibility_lib/compatibility_lib/test_compatibility_checker.py
> Filter out the packages not supported

- compatibility_server/Dockerfile
- compatibility_server/compatibility_checker_server.py
- compatibility_server/deployment/deploy.yaml
- compatibility_server/requirements.txt
- take export_metrics flag via environment variable
- update requirements.txt with hidden dependencies from opencensus
> fix docker issues

- compatibility_lib/setup.py
> Prepare for 0.1.1 release

- compatibility_lib/compatibility_lib/compatibility_store.py
- compatibility_lib/compatibility_lib/configs.py
- compatibility_server/configs.py
This was moved out from google-cloud-python repo.
> Replace google-cloud-ndb with googleapis/python-ndb

- compatibility_lib/compatibility_lib/test_utils.py
- compatibility_lib/compatibility_lib/utils.py
- update function names
- update test names
> bigquery clean up

- compatibility_lib/compatibility_lib/compatibility_store.py
- compatibility_lib/compatibility_lib/fake_compatibility_store.py
- fix docstring typos
- update fake compatibility store
> update compatibility store

- badge_server/main.py
- made changes reflecting updated badge server PRD
- introduced dicts that will assist in badge status conversion
- fix naming
> prepare for PRD changes amended

- badge_server/main.py
- refactor code to use this method
> define get_highest_status() under BadgeStatus

- badge_server/main.py
- badge_server/test_badge_server.py
improve details when a package does not support a version of python
> clean up _get_pair_compatibility_dict()

- badge_server/main.py
- badge_server/templates/one-badge.html
- badge_server/test_badge_server.py
- compatibility_lib/compatibility_lib/fake_compatibility_store.py
- also fixes target page readability
> Fix logic for finding missing data

- badge_server/test_badges.py
- the case where at least one package in a pair check does not support the given version
>  expand test coverage

- badge_server/test_badges.py
add `dependency_info` to existing `CompatibilityResult`s in `test_badges`
> add dep info to existing CRs

- badge_server/test_badges.py
- add tests for old dependencies
- add tests for obsolete dependencies
> add dependency tests

- badge_server/main.py
- badge_server/test_badge_server.py
- badge_server/test_badges.py
Please review
- covers unknown package, missing data, self incompatible cases
- todo: add details page testing for dependency tests, add test suite for pair incompatibility
> [review requested] add details page testing

- badge_server/test_badges.py
- add GOOGLE_API_CORE_SELF_INCOMPATIBLE_DATA
- update self incompatible tests to represent the data model
> update self incompatible tests to represent the data model

- compatibility_server/pip_checker.py
- decouple `client_repo_directory` from `opencensus` packages
> fix kokoro timeout

- compatibility_lib/compatibility_lib/deprecated_dep_finder.py
> Improve get_deprecated_dep by calling PyPI using a thread pool.

- compatibility_lib/compatibility_lib/get_compatibility_data.py
This matches the current production compatibility server configuration.
> Update maximum workers to 400
